sudo: required
services:
  - docker
before_install:
  - docker pull surendrajat/twrp-builder:latest
before_script:
  - cd $HOME && mkdir twrp
  - wget -q https://github.com/TwrpBuilder/twrp-sources/releases/download/omni_twrp-5.1.1-cleaned/omni_twrp-5.1.1_cleaned.tar.xz
    -O $HOME/twrp.tar.xz
  - tar -xJf twrp.tar.xz --directory $HOME/twrp/ && rm twrp.tar.xz
script:
  - cd $HOME/twrp/ && git clone https://github.com/dbzdivik/android_device_rockchip_rk3288.git device/rockchip/rk3288
  - git clone https://github.com/TwrpBuilder/android_device_generic_twrpbuilder.git device/generic/twrpbuilder
  - git clone https://github.com/omnirom/android_bootable_recovery.git bootable/recovery --depth=1
  - |
    docker run --rm -i -v "$(pwd):/root/twrp/:rw,z" surendrajat/twrp-builder bash << EOF
    cd /root/twrp/
    source build/envsetup.sh && lunch omni_rk3288-eng && make -j16 recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/rk3288/recovery.img $HOME/twrp/TWRP-$version-rk3288-$(date +"%Y%m%d").img

deploy:
  skip_cleanup: true
  provider: releases
  file_glob: true
  api_key:
    secure: Pw3WXMm79M+LKBk7vjgAMkp4Xecs3O22GUD73Y1uCXxOJANsxeKUOZ13nrlJ9kUS4acDh7q+viBPzMWY6asdOZownSY0DWVySJWC6HNDBvx8GwaiBHvOQsuklfHoOKrzpRlqphkJ1exMHf9zphP00cQ28VQHfbEvAiHSQGUAINvgjS7y3vda3CIwwhrj6OWMdnV/vg4tGPWOS0Kae+ZfH04PMPQyax7wasgbz8GqrIPwO2fCgcnuwxa+Uz1CYF1GcmCfmrreDwBtElRKoaSMcH15Q4WpxySKKEazTbaH5PKsGuKhBfQvmGLVBojVOyiTzquodleZphRmH4yRvQlBPWiwaRnC+Qy1Um5tZOOhsA9Cd+E5a+3HMlczFaSLlFuW7ujYsScSf2a6gj8pQ2HtrOkOy8w/IY33GngdKsLrNXDIz0nOxKLTCagCYj6hkt0AiA73y0nRQlA/pW6+wep6YYiBOtIxLLitEO4Ua+T8kF9Csk6DzK3rOeJDDH+sHQrTJWqWfEWlC5fr3f8/uK+HCx5y9gYByzHgowLz5RIkE7CIrQgJtEvym2qhZA4PG62HVY2t6+sRUB2F40bqxnji2DdyECq3J7H3r5HRT6q8UDsyR9hZL5WAqdLHxgIiBBEmIYQQnDHLANBVrNiWMcpzaB2gmYUkpLyxL22XZL4q0TI=
  file: "$HOME/twrp/*.img"
  on:
    tags: false
    repo: dbzdivik/android_device_rockchip_rk3288
    branch: master
branches:
  except:
    - /^(?i:untagged)-.*$/
